import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // ⚠ Generated by `npm run cf:build`. ESLint flat config does NOT read
    // .gitignore, so without this line lint reports hundreds of problems in
    // OpenNext's own bundled output the moment anyone builds before linting
    // — and reports none if they lint first, which is why this went
    // unnoticed on the first pass.
    ".open-next/**",
  ]),
]);

export default eslintConfig;
